name: OLM CLI Setup
description: Install OLM CLI

inputs:
  version:
    description: Version of OLM CLI to install
    # renovate: datasource=github-releases depName=defenseunicorns/uds-dot-mil extractVersion=^olm-(?<version>.+)$
    default: 0.1.19
  github-token:
    description: The GITHUB_TOKEN secret
    required: true

runs:
  using: composite
  steps:
    - name: Login to GHCR
      shell: bash
      run: |
        echo "${{ inputs.github-token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Install OLM CLI
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
      run: |
        uds zarf package deploy oci://ghcr.io/defenseunicorns-udm/olm-installer:${VERSION}-linux -a amd64 --confirm
        chmod +x olm
