name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v6.0.2
      # TODO: Update pinned shas once scan/vouch actions are merged.

      - name: UDS CLI Setup
        uses: defenseunicorns-udm/udsmil-common/.github/actions/uds-cli-setup@f366c21d12c7699f7db5eabe7cde129071bdee79

      # Lint logic is owned by the calling repo via a UDS task.
      # Define a 'lint' task in your tasks.yaml that runs your linter(s).
      - name: Witness Run Lint
        # TODO: replace <sha> with the commit SHA after this change is merged to main
        uses: defenseunicorns-udm/udsmil-common/src/witness-run@main
        with:
          step: lint
          enable-archivista: false
          enable-sigstore: true
          command: uds run lint:all
          outfile: lint-witness.json

      - name: Upload lint artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: lint-artifacts
          path: lint-witness.json

  scan-and-vouch:
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: UDS CLI Setup
        uses: defenseunicorns-udm/udsmil-common/.github/actions/uds-cli-setup@f366c21d12c7699f7db5eabe7cde129071bdee79

      - name: Download lint artifacts
        uses: actions/download-artifact@v8.0.1
        with:
          name: lint-artifacts
          path: .

      - name: Security Scan
        id: scan
        uses: defenseunicorns-udm/udsmil-common/.github/actions/security-scan@f366c21d12c7699f7db5eabe7cde129071bdee79

      - name: Vouch
        uses: defenseunicorns-udm/udsmil-common/.github/actions/vouch@f366c21d12c7699f7db5eabe7cde129071bdee79
        with:
          attestations: ${{ steps.scan.outputs.witness-files }},lint-witness.json
          sarif-files: ${{ steps.scan.outputs.sarif-files }}
          olm-catalog: cat-api.uds-mil.us
          olm-org: uds-army-demo
          olm-user-id: ${{ secrets.OLM_USER_ID }}
          olm-password: ${{ secrets.OLM_PASSWORD }}

  publish:
    needs: scan-and-vouch
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: UDS CLI Setup
        uses: defenseunicorns-udm/udsmil-common/.github/actions/uds-cli-setup@f366c21d12c7699f7db5eabe7cde129071bdee79

      - name: Publish
        uses: defenseunicorns-udm/udsmil-common/.github/actions/publish@f366c21d12c7699f7db5eabe7cde129071bdee79
        with:
          registry: registry.uds-mil.us
          registry-org: uds-army-demo
          registry-user-id: ${{ secrets.DEMO_ORG_USER_ID }}
          registry-password: ${{ secrets.DEMO_ORG_PASSWORD }}
