name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: UDS CLI Setup
        uses: ./.github/actions/uds-cli-setup

      - name: Witness Run Lint
        uses: ./.github/actions/witness-run
        with:
          step: lint
          command: uds run lint
          outfile: lint-witness.json

      - name: Upload lint artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: lint-artifacts
          path: lint-witness.json

  test-tasks:
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: UDS CLI Setup
        uses: ./.github/actions/uds-cli-setup

      - name: Run task integration tests
        run: uds run test

  scan-and-vouch:
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: UDS CLI Setup
        uses: ./.github/actions/uds-cli-setup

      - name: Download lint artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: lint-artifacts
          path: .

      - name: Security Scan
        run: |
          uds run scan:security \
            --with opengrep_scan_path=src/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Vouch
        run: |
          uds run vouch:package \
            --with github_token="${{ secrets.GITHUB_TOKEN }}" \
            --with olm_cat="${{ secrets.OLM_CAT }}" \
            --with olm_org="${{ secrets.OLM_ORG }}" \
            --with attestations="gitleaks-witness.json,opengrep-witness.json,lint-witness.json" \
            --with sarif_files="gitleaks.sarif.json,opengrep.sarif.json"

      - name: Upload Zarf package artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: zarf-package
          path: zarf-package-*.tar.zst

  publish:
    needs: scan-and-vouch
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: UDS CLI Setup
        uses: ./.github/actions/uds-cli-setup

      - name: Download Zarf package artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: zarf-package
          path: .

      - name: Publish
        run: |
          uds run publish:zarf-package \
            --with registry_org="${{ secrets.REGISTRY_ORG }}" \
            --with registry_user_id="${{ secrets.REGISTRY_USER_ID }}" \
            --with registry_password="${{ secrets.REGISTRY_PASSWORD }}"
